[package]
name = "sqlx-inline-fmt"
version = "0.3.0"
edition = "2024"
description = "Format inline sqlx query strings in Rust"
categories = ["command-line-utilities", "development-tools"]
keywords = ["cli", "formatter", "sqlx"]
license = "MIT"
repository = "https://github.com/code-trust/sqlx-inline-fmt"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
litrs = "1.0"
shlex = "1"
tree-sitter = "0.26"
tree-sitter-rust = "0.24"
walkdir = "2"

[lints.clippy]
branches_sharing_code = "warn"
cloned_instead_of_copied = "warn"
elidable_lifetime_names = "warn"
explicit_into_iter_loop = "warn"
explicit_iter_loop = "warn"
flat_map_option = "warn"
from_iter_instead_of_collect = "warn"
ignored_unit_patterns = "warn"
manual_string_new = "warn"
map_unwrap_or = "warn"
needless_pass_by_value = "warn"
needless_raw_string_hashes = "warn"
non_std_lazy_statics = "warn"
or_fun_call = "warn"
redundant_clone = "warn"
redundant_else = "warn"
semicolon_if_nothing_returned = "warn"
str_to_string = "warn"
type_repetition_in_bounds = "warn"
uninlined_format_args = "warn"
unnecessary_semicolon = "warn"
use_self = "warn"
